<a href="https://colab.research.google.com/github/Bibek-Poudel8/seventh-sem-project/blob/bibek/ml/notebooks/Model_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('/content/drive/MyDrive/SeventhSemMl/transaction_dataset.csv')

In [7]:
df.head()

  transaction_description              category    country currency
0                    Wage                Income        USA      USD
1    Arby's (Contactless)         Food & Dining  AUSTRALIA      AUD
2    Occupational Therapy  Healthcare & Medical        USA      USD
3   Potbelly Store Branch         Food & Dining         UK      GBP
4      Amazon - AUSTRALIA     Shopping & Retail  AUSTRALIA      AUD

In [8]:
df.tail()

               transaction_description           category country currency
4501038         Point of Sale Shopping  Shopping & Retail     USA      USD
4501039   Dining Out - Thai Restaurant      Food & Dining     USA      USD
4501040                         500.00  Shopping & Retail     USA      USD
4501041  Dining Out - Sushi Restaurant      Food & Dining     USA      USD
4501042                Earnings Credit             Income     USA      USD

In [10]:
df.shape

(4501043, 4)

In [11]:
df[df.duplicated()]

,transaction_description,category,country,currency
158,Trampoline Park,Entertainment & Recreation,CANADA,CAD
261,Occupational Therapy,Healthcare & Medical,USA,USD
375,Water Park,Entertainment & Recreation,CANADA,CAD
447,TJ Maxx,Shopping & Retail,INDIA,INR
603,Medicare,Government & Legal,AUSTRALIA,AUD
...,...,...,...,...
4500993,H&M,Shopping & Retail,UK,GBP
4500995,Whole Foods Store,Food & Dining,CANADA,CAD
4500996,Temple Store Online,Charity & Donations,AUSTRALIA,AUD
4500997,Medicaid Store,Government & Legal,INDIA,INR
4500999,Passport,Government & Legal,INDIA,INR

In [12]:
print(df.isnull().sum())

transaction_description    0
category                   0
country                    0
currency                   0
dtype: int64